[package]
name = "randomprime"
version = "0.1.4"
authors = ["April Wade <wayedt@gmail.com>"]

[dependencies]
clap = "2.9"
flate2 = "0.2"
memmap = "0.4"
preferences = "1.1"
sha2 = "0.7"
rand = "0.4"
winapi = "0.3"

structs = { path = "structs" }

[profile.release]
lto = true
panic = "abort"

[workspace]
members = ["structs", "reader_writer", "auto_struct_macros"]
