[package]
name = "randomprime_patcher"
version = "0.1.3"
authors = ["April Wade <wayedt@gmail.com>"]

[dependencies]
memmap = "0.4"
rust-crypto = "*"
rand = "0.3"
flate2 = "0.2"
clap = "2.9"

structs = { path = "structs" }

[profile.release]
lto = true
panic = "abort"

[workspace]
members = ["structs", "reader_writer", "auto_struct_macros"]
