[package]
name = "structs"
version = "0.1.0"
authors = ["Tyler Wade <wayedt@gmail.com>"]

build = "build.rs"
workspace = ".."

[dependencies]
reader_writer = { path = "../reader_writer" }

[build-dependencies]
auto_struct_macros = { path = "../auto_struct_macros" }
