[package]
name = "configurer"
version = "0.1.0"
authors = ["Tyler Wade <wayedt@gmail.com>"]

[dependencies]
memmap = "0.4"
rust-crypto = "*"
rand = "*"
flate2 = "0.2.14"

structs = { path = "../structs" }

[profile.release]
lto = true

