[package]
name = "reader_writer"
version = "0.1.0"
authors = ["Tyler Wade <wayedt@gmail.com>"]

[dependencies]
byteorder = "0.5"
generic-array = "0.5"
num = "0.1"
linked-list = { git = "https://github.com/contain-rs/linked-list.git", rev = "8c1931c74cf4cb4ad829593965e3b5101cfb4672" }
